### ISSUE TITLE
Site Section Manager: when users change their password they aren't able to see their pages

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/jc-user-roles#10]
Morning!
Just wanted to let you know of a bug in the site section user role. I got a call yesterday from a developer in the library who said she changed her password and after she logged back in with her new password her library pages were gone and some random pages were showing up in the pages list instead. I went back into her profile under my admin rights and noticed that it took out the library as one of her site sections. I was able to assign the library as a site section and that seemed to fix things.

I did a test with the test user account and sure enough, when a new password is generated it seems to wipe out any site sections that a person belongs to.

Thanks!
Ashley

**Comment by banksashleym** [comment]
UPDATE: Actually now that I'm playing around with it, any time a site section manager is updating their profile it is removing the site section when they log back in.

**Comment by banksashleym** [comment]
Damn, I was trying to test this out and was switching between branches to see if this was fixed in any, and I switched to "bug fixes" and I think I screwed it up again where I can't change branches :( Sorry!

Would you be able to tell me if this bug fix is located within a certain branch? Thanks!

**Comment by joelworsham** [comment]
Hmmm, I'm not seeing what you're seeing. The plugin still appears to have branch switching available: https://i.imgur.com/u47uF4T.png.

The branch you are looking for is `issue/10/user-sections-bug`. If I can help any further, let me know.

**Comment by banksashleym** [comment]
I can switch the plugins, but when I switch the themes area to check other branches there are no options to choose another branch.

I switched this plugin and checked this issue, thanks for fixing, it looks great!

**Comment by joelworsham** [comment]
Okay great! I'll check into why the theme isn't switching.

**Comment by joelworsham** [comment]
All set on the theme. Now that we're using this new branch switching system, some of the older branches aren't setup properly to use it, which is my fault. The ideal situation is that ALL branches will switch back and forth with no issue. I'll make sure all of the branches are up to date with this, or deleted.

Sorry about that inconvenience!

**Comment by banksashleym** [comment]
Thanks so much! Sorry about that, I'll try not to break it again :)
